Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You
have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10
jobs data.

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You
have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.


Q3:You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company name, experience required.
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs

In [1]:
import selenium
from selenium import webdriver
import time
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import time
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

In [27]:
driver=webdriver.Chrome()

In [3]:
job_info={1:['Data Analyst','Banglore'],2:['Data Scientist','Banglore'],3:['Data Scientist','Delhi/NCR']}
for itemKey,itemValue in job_info.items():
    job_title=[]
    job_location=[]
    company_name=[] 
    experience_required=[]
    driver.get('https://www.naukri.com/')
    search_field_designation=driver.find_element_by_class_name('suggestor-input')
    search_field_designation.send_keys(itemValue[0])
    search_field_location=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div/input')
    search_field_location.send_keys(itemValue[1])
    search_button=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
    search_button.click()
    url=driver.current_url
    driver.get(url)
    time.sleep(2)
    if(itemKey==3):
        element=driver.find_element(By.ID,value="chk-3-6 Lakhs-ctcFilter-")
        driver.execute_script("arguments[0].click();", element) 
        time.sleep(2)
    title_tags=driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
    company_tags=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
    job_tags=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')
    experience_tags=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]')
    elementCount=len(title_tags[0:10])
    for i in range(elementCount):
        title=title_tags[i].text
        job_title.append(title)
        cname=company_tags[i].text
        company_name.append(cname)
        jloc=job_tags[i].text
        job_location.append(jloc)
        exp=experience_tags[i].text
        experience_required.append(exp) 
    datafamename=itemKey
    datafamename=pd.DataFrame({'Title':job_title,'Location':job_location,'Company Name':company_name,'Experience Required':experience_required})
    left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
    display(left_aligned_datafamename)
#driver.close()

Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
1. Brand

2. Product Description

3. Price

4. Discount

Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com andsearch for “sneakers” in the
search field.
You have to scrape 4 attributes of each sneaker:
1. Brand

2. Product Description

3. Price

4. Discount

In [5]:
job_info={1:['sunglasses'],2:['sneakers']}

for itemKey,itemValue in job_info.items():
    brand=[]
    product_desc=[]
    price=[] 
    discount=[]
    
    driver.get('https://www.flipkart.com/')
    time.sleep(2)
    try:
        driver.find_element(By.XPATH,value="/html/body/div[2]/div/div/button").click()
    except NoSuchElementException:
        z=1
    search_field_designation=driver.find_element(By.CLASS_NAME,value='_3704LK')
    search_field_designation.send_keys(itemValue[0])
    time.sleep(2)
    driver.find_element(By.CLASS_NAME,value='L0Z3Pu').click()
    url=driver.current_url
    driver.get(url)
    time.sleep(2)
    elements=3
    for i in range(elements):
        flag=False
        brand_tags=driver.find_elements(By.CLASS_NAME,value='_2WkVRV')
        price_tags=driver.find_elements(By.CLASS_NAME,value='IRpwTa')
        product_desc_tags=driver.find_elements(By.CLASS_NAME,value='_30jeq3')
        discount_tags=driver.find_elements(By.CLASS_NAME,value='_3Ay6Sb')
        tagCount=len(brand_tags)
        for i in range(tagCount):
            if(len(brand)<=99):
                brand_data=brand_tags[i].text
                brand.append(brand_data)
                desc_data=product_desc_tags[i].text
                price.append(desc_data)
                price_data=price_tags[i].text
                product_desc.append(price_data)
                disc_data=discount_tags[i].text
                discount.append(disc_data) 
            else:
                flag=True 
                break
        if(flag):
            break
        nextTag=driver.find_elements(By.CLASS_NAME,value='_1LKTO3')
        tagcount=len(nextTag)
        nextTag[tagcount-1].click()
        #driver.execute_script("arguments[0].click();", nextTag) 
        time.sleep(2)
    datafamename=itemKey
    datafamename=pd.DataFrame({'Brand':brand,'Product Description':product_desc,'Price':price,'Discount':discount})
    left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
    display(left_aligned_datafamename)
#driver.close()

Q7: Go to the link - https://www.myntra.com/shoes
Set Price filter to “Rs. 7149 to Rs. 14099 ” , Color filter to “Black”.

First 100 shoes data you get. The data should include “Brand” of the shoes , Short Shoe
description, price of the shoe

In [6]:
driver.get('https://www.myntra.com/shoes')
time.sleep(2)
priceFilter=driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/input")
driver.execute_script("arguments[0].click();", priceFilter) 
time.sleep(2)
colorFilter=driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/input")
driver.execute_script("arguments[0].click();", colorFilter) 
time.sleep(2)
noOfPages=2
brand=[]
shoes_desc=[]
price=[]
for i in range(noOfPages):
    flag=False
    brand_tags=driver.find_elements(By.CLASS_NAME,value='product-brand')
    price_tags=driver.find_elements(By.CLASS_NAME,value='product-price')
    product_desc_tags=driver.find_elements(By.CLASS_NAME,value='product-product')        
    tagCount=len(brand_tags)
    for i in range(tagCount):
        if(len(brand)<=99):
            brand_data=brand_tags[i].text
            brand.append(brand_data)            
            price_data=price_tags[i].text.split()[1].split("Rs.")[0]
            price.append(price_data)
            desc_data=product_desc_tags[i].text
            shoes_desc.append(desc_data) 
        else:
            flag=True 
            break
    if(flag):
        break
    driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[12]/a').click() 
    time.sleep(2)
datafamename=pd.DataFrame({'Brand':brand,'Product Description':shoes_desc,'Price':price})
left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
display(left_aligned_datafamename)

Q9: Write a python program to scrape data for first 10 job results for Data Scientist Designation in Noida
    
location. You have to scrape company name, No. of days ago when job was posted, Rating of the company.

In [7]:
company_name=[]
job_posted=[]
rating=[]
driver.get('https://www.ambitionbox.com/')
time.sleep(2)
driver.find_element(By.XPATH,value='/html/body/div[1]/nav/nav/a[6]').click()
url=driver.current_url
driver.get(url)
time.sleep(2)
search_field=driver.find_element(By.XPATH,value="/html/body/div/div/div/div[2]/div[1]/div[1]/div/div/div/div/span/input")
search_field.send_keys('Data Scientist')
driver.find_element(By.XPATH,value='/html/body/div/div/div/div[2]/div[1]/div[1]/div/div/div/button').click()
time.sleep(2)
driver.find_element(By.XPATH,value='/html/body/div/div/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[2]/div[1]/p').click()
search_field_location=driver.find_element(By.XPATH,value='/html/body/div/div/div/div[2]/div[1]/div[2]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/input')
search_field_location.send_keys('Noida')
time.sleep(2)
driver.find_element_by_xpath("//label[contains(text(),'Noida')]").click()
time.sleep(2)

company_name_tags=driver.find_elements_by_xpath('//p[@class="company body-medium"]')
job_post_tags=driver.find_elements_by_xpath('//span[@class="body-small-l"]')
rating_tags=driver.find_elements_by_xpath('//span[@class="body-small"]')
elementCount=len(company_name_tags)
j=0
for i in range(elementCount):
    
    job_posted_data=job_post_tags[j].get_attribute('innerHTML').split()[0]
    job_posted.append(job_posted_data)
    
    rating_data=rating_tags[i].get_attribute('innerHTML')
    rating.append(rating_data)

    company_name_data=company_name_tags[i].get_attribute('innerHTML')
    company_name.append(company_name_data)
    j=j+2
    
datafamename=pd.DataFrame({'Company Name':company_name,'Rating':rating,'Job posted No. of days ago':job_posted})
left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
display(left_aligned_datafamename)

Q8: Go to webpage https://www.amazon.in/
Enter “Laptop” in the search field and then click the search icon.
Then set CPU Type filter to “Intel Core i7” and “Intel Core i9” 

After setting the filters scrape first 10 laptops data. You have to scrape 3 attributesfor each laptop:
1. Title
2. Ratings
3. Price

In [8]:
title=[]
rating=[]
price=[]
processor_type={1:["/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[4]/li[11]/span/a/div/label/input"],2:["/html/body/div[1]/div[2]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[6]/ul[4]/li[12]/span/a/div/label/input"]}


for itemKey,itemValue in processor_type.items():
    driver.get('https://www.amazon.in/')
    time.sleep(2)
    search_field=driver.find_element(By.ID,value="twotabsearchtextbox")
    search_field.send_keys('Laptop')
    driver.find_element(By.ID,value="nav-search-submit-button").click()
    time.sleep(2)
    processorFilter=driver.find_element(By.XPATH,value=itemValue[0])
    driver.execute_script("arguments[0].click();", processorFilter) 
    time.sleep(2)
    #title_tags=driver.find_elements(By.CLASS_NAME,value='a-size-medium a-color-base a-text-normal')
    title_tags=driver.find_elements_by_xpath('//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    price_tags=driver.find_elements(By.CLASS_NAME,value='a-price-whole')
    rating_tags=driver.find_elements(By.CLASS_NAME,value='a-icon-alt')
    elementCount=len(rating_tags)
    j=0
    for i in range(elementCount):
        if(j<=4):
            title_data=title_tags[i].text
            title.append(title_data)
            rating_data=rating_tags[i].get_attribute('innerHTML')
            rating.append(rating_data)

            price_data=price_tags[i].text
            price.append(price_data)
        j=j+1
datafamename=pd.DataFrame({'Title':title,'Rating':rating,'Price':price})
left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
display(left_aligned_datafamename)

Q10: Write a python program to scrape the salary data for Data Scientist designation.
You have to scrape Company name, Number of salaries, Average salary, Minsalary, Max Salary.

In [10]:
job_title=[]
company_name=[] 
experience_required=[]
min_salary=[]
avg_salary=[]
max_salary=[]

driver.get('https://www.ambitionbox.com/')
time.sleep(5)
driver.find_element(By.XPATH,value='/html/body/div[1]/nav/nav/a[4]').click()
url=driver.current_url
driver.get(url)
time.sleep(2)
search_field_salaries=driver.find_element(By.XPATH,value="/html/body/div/div/div/main/section[1]/div[2]/div[1]/span/input")
search_field_salaries.send_keys('Data Scientist')
time.sleep(2)
auto_suggest=driver.find_elements(By.CLASS_NAME,value='tt_text')
auto_suggest[0].click()
time.sleep(1)

company_name_tags=driver.find_elements(By.CLASS_NAME,value='name')


title_exp_tags=driver.find_elements_by_xpath('//div[@class="salaries sbold-list-header"]')

#print(title_exp_tags[0][2].text)
salary_tags=driver.find_elements_by_xpath('//div[@class="salary-values"]')
avg_salary_tags=driver.find_elements_by_xpath('//p[@class="averageCtc"]')


elementCount=len(avg_salary_tags)
j=0
for i in range(elementCount):
    if(j<=9):        
        job_title_data=title_exp_tags[i].text.split("\r")[0].split("\n")[0]
        job_title.append(title_exp_tags[i].text.split("\r")[0].split("\n")[0])
        
        campany_name_data=company_name_tags[i].text.split("\n")[0]
        company_name.append(campany_name_data)
        
        exp_required_data=title_exp_tags[i].text.split("\r")[0].split("\n")[2]
       
        experience_required.append(exp_required_data)
    
        min_sal=salary_tags[i].text.split("\n")[0]
        min_salary.append(min_sal)
        avg_sal=avg_salary_tags[i].text
        avg_salary.append(avg_sal)
        max_sal=salary_tags[i].text.split("\n")[1]
        max_salary.append(max_sal)
        time.sleep(2)
    j=j+1
    
datafamename=pd.DataFrame({'Title':job_title,'Company Name':company_name,'Experience Required':experience_required,
                          'Minimum Sal':min_salary,'Avarage Sal':avg_salary,'Maximum Sal':max_salary})
left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
display(left_aligned_datafamename)
#driver.close()

As shown in the above page you have to scrape the tick marked attributes.These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100 reviews.

In [29]:

    rating=[]
    review_summary=[]
    full_review=[] 
    
    driver.get('https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-%20earpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKC%20TSVZAXUHGREPBFGI&marketplace')
    time.sleep(2)
    driver.find_element_by_xpath("/html/body/div[1]/div/div[3]/div[1]/div[2]/div[9]/div/div/div[5]/div/a").click()
    time.sleep(2)
    total_record=100
    for z in range(total_record):
        flag=False
        read_more=driver.find_elements_by_xpath('//span[@class="_1BWGvX"]')
        if(len(read_more)>0):
            for x in range(len(read_more)):
                time.sleep(1)
                read_more[x].click()
                
        review_sum_tags=driver.find_elements_by_xpath('//p[@class="_2-N8zT"]')
        full_review_tags=driver.find_elements_by_xpath('//div[@class="t-ZTKy"]')
        rating_tags=driver.find_elements_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
        j=0
        rating_count=len(rating_tags)
        for i in range(rating_count):
            if(len(full_review)<=99):
                review_sum_data=review_sum_tags[i].text.split("\r")[0]

                review_summary.append(review_sum_data)
                full_review_data=" ".join(full_review_tags[i].text.split("\n"))

                full_review.append(full_review_data)
                rating_data=rating_tags[i].text
                rating.append(rating_data)             
            else:
                flag=True 
                break
        if(flag):
            break
        pagination=driver.find_elements(By.CLASS_NAME,value='_1LKTO3')
        if(len(pagination)>1):
            pagination[1].click()
        else:
            pagination[0].click()
        time.sleep(2)
    datafamename=pd.DataFrame({'Rating':rating,'Review Summary':review_summary,'Full Review':full_review})
    left_aligned_datafamename = datafamename.style.set_properties(**{'text-align': 'right'})
    display(left_aligned_datafamename)
    driver.close()